### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by paulwer**
"Waffe" means weapon in german and ins therefore misused.

If the change has to be placed within a tolgee-instance, this can be closed and changed there.

Thank you

### CODE REVIEW

**Comment by paulwer** [comment]
Alternatives could be "Framework", which can be used also in German in the same way.
This would then not include libraries, for whole languages like php.

Therefore I guess Plattform is the best fit. (my POV)

**Comment by JanCizmar** [comment]
I think the "weapon" joke works the same in german...

**Comment by paulwer** [comment]
From my POV (german native), I only know this from the english language. 
My opinion: It sounds weird and i was just confused instead of thinking about the english joke.
(funny afterwards, after figuring it out)

**Comment by JanCizmar** [comment]
What do you think @eweren ?

**Comment by eweren** [comment]
I understand your opinion @paulwer. Guess we should go with "Werkzeug" (tool) to transfer the joke a bit from english to german. Or "framework" since it is more explaining - but we will lose the joke with this.

**Comment by eweren** [comment]
Same goes for if you could call rest or php a plattform 🤷‍♂️

**Comment by eweren** [comment]
Eitherway... with Wekrzeug we shouldn't have a problem

**Comment by paulwer** [comment]
seems the way to go :)

**Comment by JanCizmar** [comment]
I've fixed in the Tolgee app, so it will be released with next release. Anyway, if you would like to contribute to german translation, I can invite you to the Tolgee platform. We've translated the strings using the Tolgee Translator, so it might need a review.

**Comment by paulwer** [comment]
Good Idea.
Do you need anything from me?

**Comment by JanCizmar** [comment]
I've sent you an link via the community slack. :)

**Comment by JanCizmar** [comment]
I am closing this, since it's fixed and released already. Thanks to all! 🚀

**Pull request closed without merging**
