### PR TITLE
Create Flag Quiz (Hacktoberfest Demo) #2536

### PR DESCRIPTION
**Pull request by Vaishali785**
# Created Flag Quiz (Hacktoberfest Demo) #2536 
This PR adds Flag Quiz demo app to the Tolgee Hacktoberfest project.

# Related Issue
#2536 

## Features

- Flag-based quiz questions
- Support for English, Italian, Japanese, and Korean translations
- Responsive design using Tailwind CSS or NativeWind

## Technologies

- Expo
- Tailwind CSS / NativeWind
- Tolgee

## Screenshots

<div>
 &nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;

&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;

</div>

### CODE REVIEW

**Comment by JanCizmar** [comment]
Thanks a lot! Can you share a link to the demo and dev.to article? Thanks!

**Comment by Vaishali785** [comment]
> Thanks a lot! Can you share a link to the demo and dev.to article? Thanks!

It's native app so I couldn't host it and I tried to add video here it was not working, so I don't know how to share the demo link, just let me know I'll share it. 

Article link :: https://dev.to/vaishali785/translate-guess-build-a-flag-quiz-with-expo-and-tolgee-4cah

**Comment by marketachalupnikova** [comment]
Hi @Vaishali785 ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by Vaishali785** [comment]
> Hi @Vaishali785 ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!
> 
> https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

Hi @marketachalupnikova , thanks for the appreciation and I filled out the form on the same day it was sent. Just wanted to confirm if the results for the Hacktoberfest winners are out. If not, do you have a planned date for the announcement?

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	20	(max 20)
User Experience (UX): 	8	(max 10)
Creativity: 	10	(max 10)
Usefulness: 	7	(max 10)
Total: 	45	(max 50)
		
Your prize is	Tolgee Sticker set + Tolgee Socks + Tolgee T-shirt

**Comment by Vaishali785** [comment]
> Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀
> 
> Quality: 20 (max 20) User Experience (UX): 8 (max 10) Creativity: 10 (max 10) Usefulness: 7 (max 10) Total: 45 (max 50)
> 
> Your prize is Tolgee Sticker set + Tolgee Socks + Tolgee T-shirt


Thank you so much for the evaluation and the kind words! I'm thrilled with the result and really excited for the prize! 🎉
Could you let me know how and when I’ll receive the Tolgee Sticker set, Socks, and T-shirt? I can’t wait to get them!

**Pull request merged**
