### PR TITLE
Added demo of Weather forcast #2566

### PR DESCRIPTION
**Pull request by prathamesh424**
**Solved issue #2566**

>  Translate all labels in the App with Tolgee
> Store the project into [/demos](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder
> Add a screenshot or video demo to the PR
>  Write a short article describing your demo app on DEV.to or your blog
>  Please show your support and give a ⭐ to the Tolgee repository

**Screenshots -**
Screenshot 2024-10-29 010933
Screenshot 2024-10-29 010944
Screenshot 2024-10-29 013325

https://github.com/user-attachments/assets/ce5ddbb9-9e72-4cd1-a7e4-b181dc6550b9

**Links : -**  
1. Deployment :  [Weather-Forcast-App](https://weather-forecast24.vercel.app/)
2. Article:  [ Article](https://dev.to/prathamesh_gursal/weather-app-with-tolgee-7ak)

### CODE REVIEW

**Comment by prathamesh424** [comment]
@JanCizmar  sir added demo again with main branch as you asked  .... waiting for  marge

**Comment by JanCizmar** [comment]
Thanks a lot! Great demo!

**Comment by marketachalupnikova** [comment]
Hi @prathamesh424 ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	15	(max 20)
User Experience (UX): 	9	(max 10)
Creativity: 	8	(max 10)
Usefulness: 	8	(max 10)
Total: 	40	(max 50)
		
Your prize is	Tolgee Sticker set + Tolgee Socks	

It looks like you did not fill this form, so we can sent you the Swag, please do it to claim it!
https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Pull request merged**
