### PR TITLE
Add flagmoji demo

### LINKED ISSUE #2564: 🤩 Create Flag Emoji Converter (Hacktoberfest Demo)
372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Flag Emoji Converter 🌍

Create a simple app that converts country names into their respective flag emojis. Users can type a country name and see the corresponding flag emoji.

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

### PR DESCRIPTION
**Pull request by AJBrownson**
## Description

- Adding a new demo application in the `/demos` folder
- Addressing hacktoberfest issue: 🤩 Create Flag Emoji Converter (Hacktoberfest Demo) [#2564](#2564)
- A demo web app that accepts user inputs and displays the country's flag and also has support for the English, French and German languages

### Key Features:
- Users can enter a country name and get the country's flag as an output
- Utilizes Tolgee for translation of all labels in the app
- English, French and German languages
- Responsive and clean UI

### Screenshots
App Home Page
Select Language Option
App at Work

### Blog
 Article link [dev.to](https://dev.to/anni/building-a-country-to-flag-emoji-converter-app-with-vite-typescript-and-tolgee-29e9)

## Checklist
- [✓] I have read the Contribution Guide
- [✓] If the PR changes or adds functionality, I have updated the relevant documentation
- [✓] Translate all labels in the App with Tolgee
- [✓] Store the project into [/demos](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder
- [✓] Add a screenshot or video demo to the PR
- [✓] Write a short article describing your demo app on DEV.to or your blog
- [✓] Please show your support and give a ⭐ to the Tolgee repository

### CODE REVIEW

**Review by JanCizmar — CHANGES_REQUESTED** [review]
Great demo! 🎉 Thanks a lot! I've checked the code and it's OK. 

We just cannot accept it as submodule. Please actually add the code to the demos folder.

**Comment by AJBrownson** [comment]
@JanCizmar 
So sorry for the inconvenience
I have edited my PR and added the code to the folder

**Comment by JanCizmar** [comment]
Hey! The files are still not there. Can you please add it? Just copy all the files to the demo directory.

**Comment by AJBrownson** [comment]
> Hey! The files are still not there. Can you please add it? Just copy all the files to the demo directory.

@JanCizmar 
I have added them this time
So sorry for the inconvenience

**Comment by AJBrownson** [comment]
@JanCizmar 
Waiting for your review

**Comment by AJBrownson** [comment]
@JanCizmar 
Any chance my PR will be merged soon?

**Review by JanCizmar — APPROVED** [review]
Looks fine! Thanks a lot!

**Comment by marketachalupnikova** [comment]
Hi @AJBrownson ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	10	(max 20)
User Experience (UX): 	7	(max 10)
Creativity: 	5	(max 10)
Usefulness: 	9	(max 10)
Total: 	31	(max 50)
		
Your prize is	Tolgee Sticker set

**Comment by JanCizmar** [comment]
Because you have contributed with multiple issues, you get also the Tolgee Socks. Thanks!

**Comment by AJBrownson** [comment]
Thanks
I filled in a form a while back and I presume this is the merch I'll be
receiving
Would it be possible to receive the merch before the year ends?

**Pull request merged**
