### PR TITLE
Demo: Expense Tracker

### PR DESCRIPTION
**Pull request by fadkeabhi**
# Expense Tracker Demo for Tolgee Hacktoberfest

This PR adds an Expense Tracker demo app to the Tolgee Hacktoberfest project. The app allows users to track their expenses, including input of amounts, categories, and dates, as well as viewing spending history. 

## Related Issues
https://github.com/tolgee/tolgee-platform/issues/2567

## Features

- User authentication (registration and login)
- Add and view expenses
- Localization support using Tolgee
- Responsive design with Tailwind CSS

## Tech Stack

- Frontend: React (Vite)
- Backend: Express.js
- Database: MongoDB
- Authentication: JWT
- Styling: Tailwind CSS
- Localization: Tolgee

## Implementation Details

- The app is stored in the `/demos/expense-tracker` folder
- All labels in the app are translated using Tolgee
- The app uses a responsive design and works well on both desktop and mobile devices

## Screenshots

Thank you for considering my contribution to the Tolgee Hacktoberfest event! 🐁

### CODE REVIEW

**Review by JanCizmar — CHANGES_REQUESTED** [review]
Hello! It's a great demo! 🚀

Please include the localization data as stated in here: https://tolgee.io/js-sdk/providing-static-data

So the language switch works even without providing the API key and so it works in production.

**Comment by fadkeabhi** [comment]
> Hello! It's a great demo! 🚀
> 
> Please include the localization data as stated in here: https://tolgee.io/js-sdk/providing-static-data
> 
> So the language switch works even without providing the API key and so it works in production.

@JanCizmar Now I have added the localization files into the demo, can you take a look at it. 
Now language switch is also working without API keys.

**Review by JanCizmar — APPROVED** [review]
Thanks a lot for the contribution! 🚀

**Comment by marketachalupnikova** [comment]
Hi @fadkeabhi ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	10	(max 20)
User Experience (UX): 	8	(max 10)
Creativity: 	8	(max 10)
Usefulness: 	9	(max 10)
Total: 	35	(max 50)
		
Your prize is	Tolgee Sticker set

**Pull request merged**
