### PR TITLE
Added 4 languages with help of Tolgee

### PR DESCRIPTION
**Pull request by RashmitTopG**
Created a simple react app that simulates a dice roll, where each face of the dice corresponds to a different exercise (like push-ups, sit-ups, or squats). The app generates a workout routine based on the dice rolls for users who want a spontaneous workout!

Translated all labels in the App with Tolgee
 Stored the project into [/demos](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder
 Added a screenshot or video demo to the PR
 Link to Article : (https://dev.to/rashmit_mhatre_40c3a37e37/building-a-fun-workout-app-with-react-vite-and-tolgee-dlb)
 Please show your support and give a ⭐ to the Tolgee repository.
The live demo link to the project : https://workut-dice.vercel.app/

67c89940-5602-4088-a6cc-fca0a6b3e791
ec784264-4fc2-41c1-9b6d-43061497d7a8 (1)

### CODE REVIEW

**Comment by JanCizmar** [comment]
It's pretty nice demo. 🚀 Just please add the data into demo folder instead of using submodule.

**Review by JanCizmar — COMMENTED** [review]
You didn't add all the files.

**Comment by RashmitTopG** [comment]
The translations are in assets folder.

**Comment by RashmitTopG** [comment]
Hey @JanCizmar can you please review my latest commits !! Hope this solves the problem .

**Comment by RashmitTopG** [comment]
@marketachalupnikova can you please review this PR !?

**Review by JanCizmar — APPROVED** [review]
Looks nice! 

🚀 Please post link to demo.

**Comment by RashmitTopG** [comment]
I've just added the live demo link to the project. Feel free to check it out 😀.

**Comment by JanCizmar** [comment]
Great!

**Comment by RashmitTopG** [comment]
@JanCizmar I sincerely appreciate the time you've taken to review and merge the pull request.

**Comment by marketachalupnikova** [comment]
Hi @RashmitTopG ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	16	(max 20)
User Experience (UX): 	10	(max 10)
Creativity: 	8	(max 10)
Usefulness: 	9	(max 10)
Total: 	43	(max 50)
		
Your prize is	Tolgee Sticker set + Tolgee Socks

**Comment by RashmitTopG** [comment]
No problem, thank you!

**Pull request merged**
