### PR TITLE
Weather App Added

### PR DESCRIPTION
**Pull request by Mayank77maruti**
🤩 Create weather app #2566 

- [x]  Translate all labels in the App with Tolgee
- [x]  Store the project into [/demos](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder
- [x]  Add a screenshot or video demo to the PR
- [x]  Write a short article describing your demo app on DEV.to or your blog
- [x]  Please show your support and give a ⭐ to the Tolgee repository

Image 
lol1

Click here to see my project -
Link
[Live Link](https://weather-alpha-navy.vercel.app/)
[dev.to](https://dev.to/mayank_mohapatra/weather-appwith-tolgee-3bhh)

### CODE REVIEW

**Comment by Mayank77maruti** [comment]
Hey @JanCizmar , Please do review the pr.
and
Thank you so much for taking time and reviewing all the prs.

**Comment by Mayank77maruti** [comment]
Hey @JanCizmar , Please do review the pr.
and
Thank you so much for taking time and reviewing all the prs.

**Comment by Mayank77maruti** [comment]
Hey @JanCizmar , Please do review the pr.

**Review by JanCizmar — APPROVED** [review]
Looks good! Thanks! 🚀

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	15	(max 20)
User Experience (UX): 	9	(max 10)
Creativity: 	8	(max 10)
Usefulness: 	9	(max 10)
Total: 	41	(max 50)
		
Your prize is	Tolgee Sticker set + Tolgee Socks

**Comment by JanCizmar** [comment]
Since you have sumbitted multiple PRs, we will send you the whole package containing `Your prize is Tolgee Sticker set + Tolgee Socks + Tolgee T-shirt`

**Pull request merged**
