### PR TITLE
New dream recorder

### PR DESCRIPTION
**Pull request by RashmitTopG**
Created a new Branch for Dream Recorder .  Made this app with react using tolgee.

Tolgee3
Tolgee2
Tolgee

The dev.to article link : https://dev.to/rashmit_mhatre_40c3a37e37/creating-a-dream-recorder-using-react-vite-and-tolgee-12ap
The live preview to the project : https://dream-recorder.vercel.app/

### CODE REVIEW

**Comment by RashmitTopG** [comment]
Hi @marketachalupnikova! I wanted to check in regarding Tolgee rewards and any updates on eligibility. This is my second contribution to the Tolgee platform—the first was a project called Workout Dice. I’d love to learn more about the process for earning rewards and any updates on the goodies. Thanks in advance for any details you can provide! Have a Good Day 😊 !!

**Review by JanCizmar — APPROVED** [review]
Looks good! Thanks!

**Comment by JanCizmar** [comment]
Please rename the folder. There is a conflict.

**Comment by RashmitTopG** [comment]
Hi @JanCizmar  I wanted to check in regarding Tolgee rewards and any updates on eligibility. This is my second contribution to the Tolgee platform—the first was a project called Workout Dice. I’d love to learn more about the process for earning rewards and any updates on the goodies. Thanks in advance for any details you can provide! Have a Good Day 😊 !!

**Comment by JanCizmar** [comment]
Hello! I will evaluate the pulls and setup the award process by the end of this week!

Sorry for the delay! :)

**Comment by RashmitTopG** [comment]
@JanCizmar I renamed the folder to recordDream can you please review this one

**Comment by JanCizmar** [comment]
OK! Thanks a lot!

**Comment by marketachalupnikova** [comment]
Hi @RashmitTopG ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	15	(max 20)
User Experience (UX): 	7	(max 10)
Creativity: 	8	(max 10)
Usefulness: 	8	(max 10)
Total: 	38	(max 50)
		
Your prize is	Tolgee Sticker set

**Pull request merged**
