### PR TITLE
demo: Create Mouse Memory Game

### PR DESCRIPTION
**Pull request by kaleaditya779**
### **Create Mouse Memory Game (Hacktoberfest Demo) #2563**
This PR adds Mouse Memory Game demo app to the Tolgee Hacktoberfest project.
<hr>

### Related Issue
https://github.com/tolgee/tolgee-platform/issues/2563

### Features:

- User can choose the number of cards to play with
- Various eye relaxing color themes
- Smooth in experience
- Adequate Animation in cards

### Tech Stack:

- Frontend: HTML, JavaScript
- Backend: PHP
- Styling: CSS
- Localization: tolgee-platfom

### Implementation Details

- The app is stored in the /demos/mouse-memory-game
- All labels in the app are translated using Tolgee
- The app uses a responsive design and works well on both desktop and mobile devices

### Screenshots:
Screenshot 2024-10-14 020231
Screenshot 2024-10-14 014025
Screenshot 2024-10-14 014235
Screenshot 2024-10-14 020310
Screenshot 2024-10-14 020353
Screenshot 2024-10-14 020445

### Short Video:

https://github.com/user-attachments/assets/ae8cb3ee-b428-431b-8055-c6c16333eb15

### CODE REVIEW

**Review by JanCizmar — CHANGES_REQUESTED** [review]
Hello! It's a great demo! 🚀

The problem is that you're not using Tolgee for localization. You need to implement language switch and implement the language changing logic according to the Tolgee docs.

**Comment by kaleaditya779** [comment]
> Hello! It's a great demo! 🚀
> 
> The problem is that you're not using Tolgee for localization. You need to implement language switch and implement the language changing logic according to the Tolgee docs.

I will correct that thing Sir.

**Review by JanCizmar — APPROVED** [review]
Hello! Great demo with plain PHP and JS! 🎉

**Comment by JanCizmar** [comment]
It just looks like you're using some outdated version of Tolgee JS script. May I ask where did you found it, so we can update the document? Thanks!

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	13	(max 20)
User Experience (UX): 	9	(max 10)
Creativity: 	9	(max 10)
Usefulness: 	9	(max 10)
Total: 	40	(max 50)
		
Your prize is	Tolgee Sticker set + Tolgee Socks

**Pull request merged**
