### PR TITLE
Add Country Matching Game demo with Tolgee integration

### LINKED ISSUE #2537: 🤩 Create Country Matching Game (Hacktoberfest Demo)
372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Country Matching Game 🌍

 Create a simple matching game where users have to pair countries with their respective languages, capitals, or cultural symbols (like famous landmarks or traditional foods).

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

### PR DESCRIPTION
**Pull request by mohitrajsinha**
This PR introduces the `Country Matching Game` demo app, showcasing the integration of Tolgee for localization in `Flutter`. The app allows users to match countries with their respective cultural symbols, with `Tolgee` handling dynamic language switching and translations.

[demo](https://github.com/mohitrajsinha/tolgee-platform/tree/demos/country_matching_game/demos/country_matching_game#demo)

Reviewers:
@marketachalupnikova 

###  Checklist

- [x] Translate all labels in the App with Tolgee
- [x] Store the project into [/demos](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder
- [x] Add a screenshot or video demo to the PR
- [x] Write a short article describing your demo app on DEV.to or your blog
- [x] Please show your support and give a ⭐ to the Tolgee repository

closes #2537

### CODE REVIEW

**Review by JanCizmar — APPROVED** [review]
This is great! Thanks a lot! 🎉🚀

**Comment by marketachalupnikova** [comment]
Hi @mohitrajsinha ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	14	(max 20)
User Experience (UX): 	7	(max 10)
Creativity: 	7	(max 10)
Usefulness: 	7	(max 10)
Total: 	35	(max 50)
		
Your prize is	Tolgee Sticker set

**Comment by mohitrajsinha** [comment]
@JanCizmar Could you please update me on when I can expect to receive my Tolgee swag?

**Comment by JanCizmar** [comment]
Hey! It was all sent, I hope it will come soon! If it doesn't come in next two weeks please ping me again.

**Comment by mohitrajsinha** [comment]
Yeah, Sure. Thanks for the information.

**Comment by mohitrajsinha** [comment]
Hey @JanCizmar , It has been almost two weeks but I have not received it till now.

**Comment by JanCizmar** [comment]
@marketachalupnikova

**Comment by marketachalupnikova** [comment]
Hi @mohitrajsinha, I just sent you an email with more information. Thanks and sorry for the inconvenience!

**Pull request merged**
