### PR TITLE
Azure Cognitive machine translation

### PR DESCRIPTION
**Pull request by adirh3**
Added support for Azure Cognitive machine translation provider (only paid version).
First time developing using Kotlin, take that into consideration please.

API docs - https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-translate#request-url

### CODE REVIEW

**Comment by JanCizmar** [comment]
Hello. It looks great. Thanks a lot.

**Comment by JanCizmar** [comment]
Hey. There is a task `./gradlew ktlintFormat`, which formats the code automatically. Sometimes it fails due because lines are too long, which you have to fix manually.

**Comment by adirh3** [comment]
> Hey. There is a task `./gradlew ktlintFormat`, which formats the code automatically. Sometimes it fails due because lines are too long, which you have to fix manually.

Thanks! will fix it later this week.

**Comment by JanCizmar** [comment]
Also, to get it released with a version, the commits need to follow conventional commits standard. 

https://www.conventionalcommits.org/en/v1.0.0/

So it would be great if the PR was squashed into single commit with `feat: ` prefix.

**Comment by JanCizmar** [comment]
Sorry for my inactivity here. I am currently very busy, so I will look at it hopefully next week.

**Review by JanCizmar — APPROVED** [review]

**Comment by adirh3** [comment]
Thanks @JanCizmar! Sorry somehow missed your previous comments.

**Comment by JanCizmar** [comment]
No problem. Probably during next week I will be able to provide the custom API keys feature. :)

**Pull request merged**
