### PR TITLE
feat: Add simple properties file importer

### PR DESCRIPTION
**Pull request by benallard**
See #2042

### CODE REVIEW

**Comment by JanCizmar** [comment]
Hey! Thanks a lot for the PR! It would be great to have some tests and add the support also to front-end? Are you open to do it as well? 🚀

**Comment by benallard** [comment]
By front-end support, you mean extending the text on the page ?

And about the tests, can you point me to some related ones that can inspire me?

Thanks.

**Comment by JanCizmar** [comment]
> By front-end support, you mean extending the text on the page ?

Yes. I forgot, there is actually no front-end validation for selected files extension. So extending the text should do it. Which is hard coded in Tolgee (unfortunately), so I will fix it later. 

> And about the tests, can you point me to some related ones that can inspire me?

io.tolgee.unit.service.dataImport.processors.processors.po.PoParserTest

This one should do it.

**Comment by benallard** [comment]
Both points have been addressed. Thanks!

**Review by JanCizmar — APPROVED** [review]

**Pull request merged**
