### PR TITLE
Add Random Movie Picker Demo with Localization using Tolgee called CineCue.

### PR DESCRIPTION
**Pull request by Toprun123**
This pull request implements a random movie picker demo as part of the Tolgee Hacktoberfest event. The app allows users to input their favorite movie genres and suggests random movies based on those genres. It is built with Ruby on Rails and fully integrates with the Tolgee localization framework for multi-language support. This PR is in reference to #2545 .

### Changes Made
- **Project Structure**: Added a new demo app under the `/demos` folder as requested.
- **Random Movie Picker Feature**: Developed a feature that allows users to select their favorite genres and randomly suggest movies based on those genres.
- **Localization**: Integrated Tolgee for translating app labels and messages into multiple languages.
- **Demo Content**: Added screenshots and documentation to demonstrate the functionality of the app.
- **Article Link**: Included a link to an article on [DEV.to](https://dev.to/sixzix/cinecue-a-seamless-localization-demo-with-ror-360j) describing the demo app.

### Screenshots

HomepageEN

<details>
    <summary>Additional Screenshots</summary>

LoginHI
HomepageTR
PassUR
SignupFR

</details>

#### More information about the demo is in the ``README.md`` file

_PS: This is my first major PR so please correct me if I did anything wrong in the process. Thanks.
PS: There are a **few** cool css animations in the page that I can't take a screeenshot for.
I have also given a ⭐ to the Tolgee repository._

### CODE REVIEW

**Review by JanCizmar — CHANGES_REQUESTED** [review]
Hey! it looks great! I really appreciate the effort and app complexity.

- The only problem is that your app is relying on Tolgee servers in production.
- Can you please make it fetch the localization data from the CDN in production? Or even better you can use the Tolgee CLI to export it to the ruby format and then use the ruby native localization library. 

Your approach of parsing json returned from Tolgee REST API doesn't add much benefit since you're not able to in-context edit the string as in JavaScript frameworks.

**Comment by Toprun123** [comment]
Im sorry but I did not understand exactly -- I am getting the language translations from the tolgee RESTful api in ruby which is then parsed by the ruby jsom gem. You have to put your tolgee api-key in the `app/controllers/application_controller.rb` file.

**Comment by JanCizmar** [comment]
Tolgee has content delivery features for the production use: https://tolgee.io/platform/projects_and_organizations/content_delivery

The benefit is that the CDN servers are spread around the world and they have 100% uptime. So the production apps does rely in Tolgee API, which has ca. 99.95% uptime.

Also Tolgee supports the Ruby format for export, so you don't have fetch it from the API in json, but you can use the exported ruby YAML.

https://tolgee.io/platform/formats/ruby_yaml

**Comment by Toprun123** [comment]
Oh, Thanks ill try that.

**Review by JanCizmar — APPROVED** [review]
Thanks!

**Comment by JanCizmar** [comment]
No worries! Thanks for the contribution!

**Comment by Toprun123** [comment]
Thank you too!

**Comment by marketachalupnikova** [comment]
Hi @Toprun123 ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	19	(max 20)
User Experience (UX): 	8	(max 10)
Creativity: 	10	(max 10)
Usefulness: 	8	(max 10)
Total: 	45	(max 50)
		
Your prize is	Tolgee Sticker set + Tolgee Socks + Tolgee T-shirt

**Comment by Toprun123** [comment]
Thanks

**Pull request merged**
