### PR TITLE
Daily Joke Generator added

### PR DESCRIPTION
**Pull request by Mayank77maruti**
Solved issue #2534

- [x] Translate all labels in the App with Tolgee
- [x] Store the project into [/demos](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder
- [x] Add a screenshot or video demo to the PR
- [x]  Write a short article describing your demo app on DEV.to or your blog
- [x]  Please show your support and give a ⭐ to the Tolgee repository

Screenshots -
Screenshot 2024-10-26 143559

Article Link -
[dev.to LINK](https://dev.to/mayank_mohapatra/joke-generator-with-tolgee-2c9o)
[medium LINK](https://medium.com/@mayank.mohapatra7/joke-generator-with-tolgee-d43f499d8062)

### CODE REVIEW

**Comment by Mayank77maruti** [comment]
Hey @JanCizmar , this is pr is ready to be reviewed.
It would be really great if you can review it.
Thank you.

**Review by JanCizmar — APPROVED** [review]
Wery nice! Thanks a lot!

**Comment by marketachalupnikova** [comment]
Hi @Mayank77maruti ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by JanCizmar** [comment]
Thanks for contributing and sorry for the delay. Here is the project evaluation! 🚀

Quality: 	19	(max 20)
User Experience (UX): 	10	(max 10)
Creativity: 	8	(max 10)
Usefulness: 	9	(max 10)
Total: 	46	(max 50)
		
Your prize is	Tolgee Sticker set + Tolgee Socks + Tolgee T-shirt

**Pull request merged**
