### PR TITLE
feat: Darkmode

### PR DESCRIPTION
**Pull request by eweren**
I added some functionality to have a darkmode in the app.
-> I added [headless.ui](https://headlessui.dev/) as a new dependency in order to create this simple animation. Maybe this library could be useful in other places of the application as well as it gives the developers unstyled, but functional components and a simple transition api. Hope you enjoy

### CODE REVIEW

**Comment by stepan662** [comment]
Hey, thanks for your pull request. I've checked the changes, but I'm afraid that it will need more work as there are quite a few places which are not "contrasty" enough. Also we need to consult the color palette with our designer. I understand that you've made our main color lighter, but this is definitely too pink 😄

I'll put the dark mode in our backlog, but I can't really say when we get to it as currently we have quite a lot "core" things that we want to do, so this is not a priority now.

**Comment by stepan662** [comment]
Snímek obrazovky 2022-03-21 v 9 23 03

**Comment by JanCizmar** [comment]
If you really want to be able to use the darkmode, maybe we can hide the switch and some URL endpoint, which would enable it. So you can use it, but it won't be public.

Or we ask our designer to provide colors and design, which match our guidelines so @eweren, would be able to update it?

**Comment by eweren** [comment]
I can do as you like. For now I'll just hide the toggle and set the localStorage entry for myself. But if your designers come with a dark color scheme I can implement that as well and re-enable the theme toggle. @JanCizmar

**Comment by JanCizmar** [comment]
Great! :)

**Comment by eweren** [comment]
> I'll put the dark mode in our backlog,... 

Yes I understand that. Thank you for reviewing 🙂

**Comment by JanCizmar** [comment]
Hi, sorry for the long response.

We are going to look at it next week. Stepan will fix the styles and the code to match our guidelines and conventions. Thanks a lot for this. 👍 

I cannot merge #1003, since it would need a lot of style fixing and testing and we currently don't have capacity, to do all that. 

We are sorry for letting you wait 😞  We really appreciate your contributions, but it's hard for us to manage all the priorities. Don't hesitate to consult the the changes you are willing to do in the future. We can agree on that before you spend a lot of time on it and we can also describe our conventions and workflow. 🤟

**Comment by eweren** [comment]
Hi @JanCizmar, I totally understand that you currently have other priorities and not the capacity to spent too much time on PRs that are out of scope.

For #1003 - I thought so. That one can wait much longer or can just be closed. 

If you would add some issues that you are currently planning with and mark them with a label, contributing would be more straight forward I guess.

**Comment by KaKi87** [comment]
> We are going to look at it next week.

Just sayin', we reached the end of said week. xD
> I totally understand that you currently have other priorities

So do I, although using dark-themed apps *is* a priority for me, considering the amount of time I spend in front of screens every day.
> PRs that are out of scope

However, I don't think that this PR is out of scope, if you meant so.

**Comment by JanCizmar** [comment]
Yep. Week is over and we are overwhelmed. I consulted it with our designer. She will look into it, but it's going to take some time. (There are some issues, which were on [roadmap](https://tolgee.io/roadmap) and we are already late)

I think, we maybe will merge this to one task with updating to MUI 5 and updating styles project-wide, since this needs a full-system user testing, so maybe it would be better to do it in all in one larger task.

**Comment by stepan662** [comment]
I've started separated pull request inspired by this: https://github.com/tolgee/tolgee-platform/pull/1082
A few things I've needed to do differently

**Pull request closed without merging**
