### PR TITLE
chore: Solve Gradle 9 incompatibility issues

### PR DESCRIPTION
**Pull request by StaNov**

### CODE REVIEW

**Comment by StaNov** [comment]
@JanCizmar Could you please try it locally with billing repos present? Thank you :slightly_smiling_face:

**Comment by JanCizmar** [comment]
It works

**Comment by StaNov** [comment]
@JanCizmar Perfect, I would suggest to merge it then.

**Comment by StaNov** [comment]
And the deprecation notice is gone 🙂

Before: https://github.com/tolgee/tolgee-platform/actions/runs/11856971389/job/33044345608#step:7:75

After: https://github.com/tolgee/tolgee-platform/actions/runs/11818182532/job/33040495032#step:7:75

**Pull request merged**
