### PR TITLE
Added demo of Event  Countdown Timer #2568

### PR DESCRIPTION
**Pull request by prathamesh424**
**Solved issue #2568**

>  Translate all labels in the App with Tolgee
> Store the project into [/demos](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder
> Add a screenshot or video demo to the PR
>  Write a short article describing your demo app on DEV.to or your blog
>  Please show your support and give a ⭐ to the Tolgee repository

**Screenshots -**
Screenshot 2024-10-24 210448
Screenshot 2024-10-24 210458
Screenshot 2024-10-24 023633

**Links : -**  
1. Deployment :  [counter-timer](https://countdown-180.vercel.app/)
2. Article:  [ Article](https://dev.to/prathamesh_gursal/countdown-timer-with-tolgee-5d56)

### CODE REVIEW

**Comment by prathamesh424** [comment]
@JanCizmar  all task completed and links are added

**Comment by prathamesh424** [comment]
@JanCizmar , @marketachalupnikova   all task completed and links are added

**Comment by prathamesh424** [comment]
@JanCizmar  can you check out I want to make another PR

**Comment by prathamesh424** [comment]
@JanCizmar  sir please check out

**Review by JanCizmar — APPROVED** [review]
Looks great! Thanks a lot 🚀

**Comment by marketachalupnikova** [comment]
Hi @prathamesh424 ! Thanks again for your Hacktoberfest 2024 contribution! 🎉 Please fill out this survey so we can send your reward!

https://app.formbricks.com/s/cm375z4j6000amd4zgh5b3ycg

**Comment by JanCizmar** [comment]
Hello! Since you have contributed to multiple PRs, you will get the full package of `Tolgee Sticker set + Tolgee Socks + Tolgee T-shirt`. Thanks a lot!

**Pull request merged**
