### PR TITLE
fix: Add state to oauth2 redirect url and validate that

### PR DESCRIPTION
**Pull request by waigel**

### CODE REVIEW

**Comment by waigel** [comment]
Can we upgrade typescript to > 4.6.2 to fix this issue?

**Comment by stepan662** [comment]
Yeah, feel free to update it, but also the login e2e test is failing.

**Comment by stepan662** [comment]
The "namespace" one is flaky, so you can ignore that one (it should be fixed in main).

**Comment by JanCizmar** [comment]
It still fails on main time to time, so you can be brave and fix it! 💪 I spend few hour on it, making it less flaky.

**Pull request closed without merging**
