### PR TITLE
Add Cuisine Explorer Demo 🍕 to Demos Folder

### PR DESCRIPTION
**Pull request by Mefisto04**
#### Description
This PR introduces the **Cuisine Explorer** app, a simple application that allows users to explore traditional dishes from different countries and regions. The app has been built using React and utilizes **Tolgee** for in-context translations, ensuring that all labels are translated for a seamless user experience.

#### Key Features:
- Introduces users to a diverse range of traditional dishes.
- Utilizes Tolgee for translation of all UI labels.
- Responsive design with an engaging user interface.
- Search and filter options for finding specific dishes easily.

#### Project Structure
The project has been stored in the `/demos` folder.

#### Demo
- Screenshot:
image

- Blog Link: https://dev.to/mefisto04/unveiling-dishhub-a-culinary-journey-with-tolgee-3ihi

---

### Checklist:
- [x] Code is well-documented and follows best practices.
- [x] All labels in the app are translated using Tolgee.
- [x] A screenshot or video demo is included in the PR.
- [x] A blog post describing the demo app is provided.

### CODE REVIEW

**Review by JanCizmar — CHANGES_REQUESTED** [review]
Hello! It's a beautiful demo! 🚀

The only thing missing is implementing language switch and localization using Tolgee. When this is implemented, we are ready to roll.

**Comment by Mefisto04** [comment]
@JanCizmar 
Implemented Translation and Localization
Added localization support using Tolgee, including translation functions for dish search and filter buttons, enhancing accessibility for users in multiple languages.

**Review by JanCizmar — CHANGES_REQUESTED** [review]
Thanks for the demo 🎉
- Link for demo is missing
- Link for dev.to article is missing
- The localization jsons cointain only the official demo strings (it should be exported so the app is ready for production without leaking the Tolgee API key)
- The unused Tolgee example files should be deleted
- You have changed quotes in the example demo breaching our code style -> revert it
-

**Comment by JanCizmar** [comment]
Hello! Any updates?

**Pull request closed without merging**
