### PR TITLE
Dream recorder

### PR DESCRIPTION
**Pull request by RashmitTopG**
Created Dream Recorder using React+VIte and added Language Support Using Tolgee.

### CODE REVIEW

**Comment by RashmitTopG** [comment]
Is there any way to dynamically translate the dreams that will be added without them being already translated and saved as keys.

**Review by JanCizmar — CHANGES_REQUESTED** [review]
Hello! It's a great demo! 🚀

Please add the localization jsons to the code or use CDN, so the localization works even withtout providing the API key.

**Comment by JanCizmar** [comment]
@RashmitTopG We don't have to translate the dreams since it's user defined content, which is out-of-scope for Tolgee. Usually you can use services like DeepL or Google Translate, but we don't have to cover this in the demo.

**Comment by RashmitTopG** [comment]
Hey !@JanCizmar can you please review the changes and also check my other PR for Demo Workout Dice

**Comment by JanCizmar** [comment]
Hello! Where can I find the link for demo and dev.to article?

**Comment by RashmitTopG** [comment]
Thank you for your patience. I will make sure to add them by the end of the
day today.

**Comment by RashmitTopG** [comment]
I will add the live link and blog by EOD can you open the issue ??

**Comment by JanCizmar** [comment]
It seems like there already is a dreamRecorder. So maybe you need to rename the folder?

**Comment by JanCizmar** [comment]
Any updates to this?

**Comment by RashmitTopG** [comment]
@JanCizmar made a new PR for the dreamRecorder . Sorry for the delay .

**Pull request closed without merging**
