### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kushal34712**
Added French Language option to the main readme file so that it can be directly accessible from there

### CODE REVIEW

**Comment by JanCizmar** [comment]
This can be done in the same PR as the french translation.

**Comment by kushal34712** [comment]
sir i have add the path the the french language in the main readme file do check it once

**Comment by kushal34712** [comment]
that time i have forget to add so I am adding now

**Comment by JanCizmar** [comment]
You can update that PR. You don't have to create new one.

**Pull request closed without merging**
