### PR TITLE
Change Java from 17 to 21

### PR DESCRIPTION
**Pull request by M3rcena**
It currently builds and run correctly using Java 21 so its a good update.

### CODE REVIEW

**Comment by JanCizmar** [comment]
Hey! Why did you update the npm packages?

**Review by JanCizmar — COMMENTED** [review]
We will also need to update the docker images to java 21. This is on me.

**Comment by M3rcena** [comment]
> Hey! Why did you update the npm packages?

So they had severe vulnerabilities especially with the packages you use. It's a security flaw while they were outdated for a long time..

Also there is another security flaw which needs to be resolved. I will tell you in Slack while it's not good to mention it here

**Comment by M3rcena** [comment]
> We will also need to update the docker images to java 21. This is on me.

Of course! I could do it but if you want it's all yours

**Comment by M3rcena** [comment]
> We will also need to update the docker images to java 21. This is on me.

Also consider updating and changing the builder because it's deprecated with the latest Gradle versions.

**Comment by JanCizmar** [comment]
What do you mean by the builder?

**Comment by M3rcena** [comment]
> What do you mean by the builder?

If you go and build the docker image you will see you will get a Deprecated message for Gradle 9.0 because you have set the docker builder to 0. You need to either update the builder so it's not deprecated or use the docker builder itself, the builder kit

**Comment by JanCizmar** [comment]
I cannot see update of Gradle in your PR. How are you actually running it?

**Comment by M3rcena** [comment]
I also removed jCenter()

image

**Pull request closed without merging**
